version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: ./project-back/config/Dockerfile.database
    environment:
      POSTGRES_USER: myapp
      POSTGRES_PASSWORD: mySeKreTPassW0rDD
      POSTGRES_DB: myapp
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: ./project-back/config/Dockerfile.app
    environment:
      DB_HOST: database
      DB_USER: myapp
      DB_PASSWORD: mySeKreTPassW0rDD
      DB_NAME: myapp
      DB_PORT: 5432
    ports:
      - "5000:5000"
    depends_on:
      - database

volumes:
  db_data:
